[Auth]
client_id=""
client_secret=""
redirect_uri="https://www.google.com/"
scope="""user-read-recently-played,playlist-modify-public,playlist-modify-private,user-modify-playback-state,user-top-read,user-read-playback-position
,playlist-read-private,user-library-read,user-follow-modify,user-follow-read"""